# permissions for end users to edit deploymentsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentset-editor-role
rules:
- apiGroups:
  - alexec.alexec
  resources:
  - deploymentsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alexec.alexec
  resources:
  - deploymentsets/status
  verbs:
  - get
