# permissions for end users to view deploymentsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentset-viewer-role
rules:
- apiGroups:
  - alexec.alexec
  resources:
  - deploymentsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alexec.alexec
  resources:
  - deploymentsets/status
  verbs:
  - get
